"""add code_symbols and code_edges tables for AST context map

Revision ID: 2f53af0f20e6
Revises: 1298bc0f9253
Create Date: 2026-07-12 12:47:53.668797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f53af0f20e6'
down_revision: Union[str, Sequence[str], None] = '1298bc0f9253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('target_file', sa.String(), nullable=True),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('source_symbol', sa.String(), nullable=True),
    sa.Column('target_symbol', sa.String(), nullable=True),
    sa.Column('raw_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_file', 'target_file', 'edge_type', 'source_symbol', 'target_symbol', name='uq_edge')
    )
    op.create_index(op.f('ix_code_edges_project_id'), 'code_edges', ['project_id'], unique=False)
    op.create_index(op.f('ix_code_edges_source_file'), 'code_edges', ['source_file'], unique=False)
    op.create_index(op.f('ix_code_edges_target_file'), 'code_edges', ['target_file'], unique=False)
    op.create_table('code_symbols',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=False),
    sa.Column('symbol_type', sa.String(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'filename', 'symbol_name', 'start_line', name='uq_symbol_location')
    )
    op.create_index(op.f('ix_code_symbols_filename'), 'code_symbols', ['filename'], unique=False)
    op.create_index(op.f('ix_code_symbols_project_id'), 'code_symbols', ['project_id'], unique=False)
    op.drop_table('cocoindex_setup_metadata')
    op.drop_table('codeembedding_5ef703e5_2a1f_4c1d_9795_e691f36084b8__cocoindex_t')
    op.alter_column('code_embeddings', 'code_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('code_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=False)
    op.alter_column('code_embeddings', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('code_embeddings__embedding__vector_cosine_ops'), table_name='code_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_code_embeddings_project_id'), 'code_embeddings', ['project_id'], unique=False)
    op.create_foreign_key(None, 'code_embeddings', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'code_embeddings', type_='foreignkey')
    op.drop_index(op.f('ix_code_embeddings_project_id'), table_name='code_embeddings')
    op.create_index(op.f('code_embeddings__embedding__vector_cosine_ops'), 'code_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('code_embeddings', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('code_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=True)
    op.alter_column('code_embeddings', 'code_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('codeembedding_5ef703e5_2a1f_4c1d_9795_e691f36084b8__cocoindex_t',
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_key', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('max_process_ordinal', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('staging_target_keys', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('memoization_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed_source_ordinal', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('processed_source_fp', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('process_logic_fingerprint', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('process_ordinal', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('process_time_micros', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('target_keys', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('source_id', 'source_key', name=op.f('codeembedding_5ef703e5_2a1f_4c1d_9795_e691f36084b8__cocoin_pkey'))
    )
    op.create_table('cocoindex_setup_metadata',
    sa.Column('flow_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('staging_changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('flow_name', 'resource_type', 'key', name=op.f('cocoindex_setup_metadata_pkey'))
    )
    op.drop_index(op.f('ix_code_symbols_project_id'), table_name='code_symbols')
    op.drop_index(op.f('ix_code_symbols_filename'), table_name='code_symbols')
    op.drop_table('code_symbols')
    op.drop_index(op.f('ix_code_edges_target_file'), table_name='code_edges')
    op.drop_index(op.f('ix_code_edges_source_file'), table_name='code_edges')
    op.drop_index(op.f('ix_code_edges_project_id'), table_name='code_edges')
    op.drop_table('code_edges')
    # ### end Alembic commands ###
