"""add surrogate UUID PK to code_embeddings

Revision ID: fc35939074d2
Revises: 
Create Date: 2026-07-07 23:47:28.396730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc35939074d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: add id column as nullable first
    op.add_column('code_embeddings', sa.Column('id', sa.String(), nullable=True))

    # Step 2: backfill UUIDs for existing rows
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("UPDATE code_embeddings SET id = gen_random_uuid()::text WHERE id IS NULL")

    # Step 3: drop the existing primary key first
    op.drop_constraint('code_embeddings_pkey', 'code_embeddings', type_='primary')

    # Step 4: now set NOT NULL and create new PK on id
    op.alter_column('code_embeddings', 'id', nullable=False)
    op.create_primary_key('pk_code_embeddings', 'code_embeddings', ['id'])

    # Step 5: add unique constraint on the old composite key columns
    op.create_unique_constraint('uq_embedding_chunk', 'code_embeddings', ['project_id', 'filename', 'location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'code_embeddings', type_='foreignkey')
    op.drop_constraint('uq_embedding_chunk', 'code_embeddings', type_='unique')
    op.drop_index(op.f('ix_code_embeddings_project_id'), table_name='code_embeddings')
    op.create_index(op.f('code_embeddings__embedding__vector_cosine_ops'), 'code_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('code_embeddings', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('code_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=True)
    op.alter_column('code_embeddings', 'code_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('code_embeddings', 'id')
    op.create_table('codeembedding_5ef703e5_2a1f_4c1d_9795_e691f36084b8__cocoindex_t',
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_key', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('max_process_ordinal', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('staging_target_keys', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('memoization_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed_source_ordinal', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('processed_source_fp', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('process_logic_fingerprint', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('process_ordinal', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('process_time_micros', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('target_keys', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('source_id', 'source_key', name=op.f('codeembedding_5ef703e5_2a1f_4c1d_9795_e691f36084b8__cocoin_pkey'))
    )
    op.create_table('cocoindex_setup_metadata',
    sa.Column('flow_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('staging_changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('flow_name', 'resource_type', 'key', name=op.f('cocoindex_setup_metadata_pkey'))
    )
    # ### end Alembic commands ###
